{% set version = "4.9.3" %}

package:
  name: lftp
  version: {{ version }}

source:
  url: http://lftp.yar.ru/ftp/lftp-{{ version }}.tar.gz
  sha256: 68116cc184ab660a78a4cef323491e89909e5643b59c7b5f0a14f7c2b20e0a29

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - autoconf
    - autoreconf
    - make
    - pkg-config
  host:
    - openssl
    - readline
    - ncurses
    - openssl
    - zlib
    - libiconv

test:
  commands:
    - lftp --version

about:
  home: https://lftp.yar.ru/
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: |
    LFTP is a sophisticated file transfer program supporting a number of network protocols
    (ftp, http, sftp, fish, torrent). Like BASH, it has job control and uses the readline
    library for input. It has bookmarks, a built-in mirror command, and can transfer
    several files in parallel. It was designed with reliability in mind.

extra:
  recipe-maintainers:
    - danielnachun
    - epruesse
    - croth1
