{% set version = "4.9.0" %}

package:
  name: lftp
  version: {{ version }}

source:
  url: http://lftp.yar.ru/ftp/lftp-{{ version }}.tar.gz
  sha256: 2f799849f54e1d7f9013a751b69732782ea13a51b32b119940637cd469111ca7

build:
  number: 0
  # Windows build fails due to missing [n]curses.h or terminfo.h
  skip: True                       # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config

  host:
    - openssl
    - readline                     # [not win]
    - ncurses                      # [not win]
    - expat
    - zlib
    - libiconv
    - gettext
    - xz

  run:
    - openssl
    - expat
    - zlib
    - libiconv
    - gettext
    - readline                     # [not win]
    - ncurses                      # [not win]

test:
  commands:
    - lftp --version

about:
  home: https://lftp.yar.ru/
  license: GPL_v3
  license_family: GPL
  license_file: COPYING
  summary: |
    LFTP is a sophisticated file transfer program supporting a number of network protocols
    (ftp, http, sftp, fish, torrent). Like BASH, it has job control and uses the readline
    library for input. It has bookmarks, a built-in mirror command, and can transfer
    several files in parallel. It was designed with reliability in mind.

extra:
  recipe-maintainers:
    - epruesse
    - croth1
