# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Ly/5Xs4Whq2jcYK9RzfMIsv2znopAHnv9yow/P0GI1kR/5zVbAH8rfp0n55aiYATXEcCA7CqBaEEwXPkXqaVdBjycqlQrlLyWtpjLiuVvKV90meXokBJTTsPq+0/owKrlYqQTkveu+vR2CHquigu3cRPJMT4uJlPplOgmzyGrMXN+3nTw/2BSrPFI7BVf2q2Pjf1GfFeAF/RXLR7cj6Stcy9mF2GsJwbU77lsw0fEX+uaXGqUWrnXqjGeI1OEx/6EjTni51fF32ywUdW0wjHuMzI5IhRzjztW0J0q/QSlFDvqTOMB7NboLOEf2CT1JhQlh9tHclydgfyfocb+8f/+W+AghqnXE+xN11ZauSg/wrg/JIXC9ByXMnm3EmUjA6y5gcfQNNrsQiWOCqL7KZVbN9IdsWirQPW2LMJgGeJ6qWTSxaovVtAAC0EfTmS8rHvdrBeuRNpaFkdunSLo+o6xZGMtDA0TVbqS4AphoOpbVqxjesUkPT1L8eTDsaa846kkFMvsZf8pE9j5JQi06iPB6UQ4pbzKCPyxWIGyvYN5QM8stZebuLs9YFWjX4WjvSQRVw11CIBxjT9JuuI9eTNElONgrMby3/9CiYKdciVh0jQ0EDH0NAMQmDXR+l53bLSmKXL6MzO0R19FJtnUe6wOWa6XgjqM54AeRZMmkPVw54="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
