appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: XoK0/aecxy7xKG4OPiUpvciHFOy1rboGJbG3/GfGmFuCC28lTq/JfkTnotLDi8SsVvxKUnxM1XtUWPLkKc1ZdSVD8xK89A9L2in8RPSg4ZDyV/H/eu0sj+KVfNf7FFJqZZ/+ME9+1r5OCWLLhrhW3xE1ap52ilKChdlDiFurhRWjXH9lVZQPMrxvz/qOm5d4vYz1Ds6mF+T+e+DKxP3F8C9qBOBe9cC9lI0G70BaidOmk3tM9WQpoHXlI/j1V3JTTSSdt727ZNmBPp33t/BE0H3+4pdlZIk2a3tTWZpLUezIIsULPfgyO67uh4by8eLW5/Kni3bRTjMRYyBSYuw9Y4vP/3vjyBLZrcS1GoYCYxtHXoxlWaWUp8hLhM7EkM0MZKhahQjfR1aahXI+sQH6sxL3qN1BJYPoStGhMoUY7qpwEThL9ZWRW5XL0OWI0XRSamIchcR8sXa2pxtQPsc2hrEpHGYKShMf/eG3JQ/+WEeYiuvVG90cqPJIwX3OkBBOjSGZZ6ZI1Fm74ugyHDHXZXcgvjMRhF5KuK/S04s1ifgbL8M7bn1KKPqWaLv7M4Da59fqqMQ/K04LDq3ibjhuY0bNXOZar+vxmhjkIt1DL70x8YL1aLt3S7VLRKIkqC39WiByMEz+e9y2K0k++iOyZ0m/MWHWh4SvPDO9AdxWubU=}
conda_forge_output_validation: true
